import type { Metadata } from "next";
import { Catamaran,Aladin, Inter } from "next/font/google";
import "./globals.css";
import Footer from "../../components/ui/Footer";
import Navbar from "../../components/ui/Navbar";

const inter = Inter({ subsets: ["latin"] });

const aladin = Aladin(
  {subsets: ["latin"],
    variable: "--font-aladin",
    display: "swap",
  weight: ["400"],}
)
const catamaran = Catamaran(
  {subsets: ["latin"],
    variable: "--font-cat",
    display: "swap",
  weight: ["100"],}
)

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
