import type { Metadata } from "next";
import { Catamaran, Aladin } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const aladin = Aladin(
  {subsets: ["latin"],
    variable: "--font-aladin",
    display: "swap",
  weight: ["400"],}
)

export const catamaran = Catamaran(
  {subsets: ["latin"],
    variable: "--font-cat",
    display: "swap",
  weight: ["100"],}
)

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
